title: MAGMA CUBE
email: admin@magmacube.studio

author:
  name: "(주)마그마큐브"
  email: "admin@magmacube.studio"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.magmacube.studio" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed
minima:
  skin: dark
show_excerpts: true

google_analytics: G-6MPZW8YEZG

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
