title: MAGMA CUBE
email: admin@magmacube.studio

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.magmacube.studio" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed
minima:
  skin: dark

show_excerpts: true
google_analytics: "G-6MPZW8YEZG"
